FROM python:3.12 AS builder

WORKDIR /app
RUN python3 -m venv .venv
COPY backend/requirements.txt .
RUN ./.venv/bin/pip3 install -r requirements.txt

FROM python:3.12-slim AS runtime

WORKDIR /app
RUN useradd -u 1000 app && \
    chown -R app /app
USER app

COPY --chown=app backend .
COPY --from=builder --chown=app /app/.venv .venv
RUN mkdir -p /app/data

ENTRYPOINT exec ./.venv/bin/fastapi run --port ${PORT:-8300} main.py